@PostService.Api_HostAddress = http://localhost:5096
@token = YOUR_JWT_TOKEN

### Create post
POST {{PostService.Api_HostAddress}}/createpost
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "description": "Test post"
}

### Profile cards
GET {{PostService.Api_HostAddress}}/user/{{userId}}/cards?page=1&pageSize=10
Authorization: Bearer {{token}}

### User feed
GET {{PostService.Api_HostAddress}}/user/{{userId}}/posts?page=1&pageSize=10
Authorization: Bearer {{token}}

### Liked posts
GET {{PostService.Api_HostAddress}}/liked?page=1&pageSize=12
Authorization: Bearer {{token}}

### Favorite posts
GET {{PostService.Api_HostAddress}}/favorites?page=1&pageSize=12
Authorization: Bearer {{token}}
