// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserService.Infrastructure.Data;

#nullable disable

namespace UserService.Infrastructure.Migrations
{
    [DbContext(typeof(DbContextUser))]
    [Migration("20260524122232_MediaUserChangeMiniO")]
    partial class MediaUserChangeMiniO
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserService.Domain.Models.BlackList", b =>
                {
                    b.Property<Guid>("MyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlackId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MyId", "BlackId");

                    b.HasIndex("BlackId");

                    b.ToTable("BlackLists");
                });

            modelBuilder.Entity("UserService.Domain.Models.FriendList", b =>
                {
                    b.Property<Guid>("MyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FriendId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeLogin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MyId", "FriendId");

                    b.HasIndex("FriendId");

                    b.ToTable("FriendLists");
                });

            modelBuilder.Entity("UserService.Domain.Models.MediaUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MediaUsers");
                });

            modelBuilder.Entity("UserService.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UserService.Domain.Models.BlackList", b =>
                {
                    b.HasOne("UserService.Domain.Models.User", "Black")
                        .WithMany("BlockedByUsers")
                        .HasForeignKey("BlackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UserService.Domain.Models.User", "My")
                        .WithMany("MyBlackList")
                        .HasForeignKey("MyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Black");

                    b.Navigation("My");
                });

            modelBuilder.Entity("UserService.Domain.Models.FriendList", b =>
                {
                    b.HasOne("UserService.Domain.Models.User", "Friend")
                        .WithMany("AddedToFriends")
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UserService.Domain.Models.User", "My")
                        .WithMany("MyFriends")
                        .HasForeignKey("MyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("My");
                });

            modelBuilder.Entity("UserService.Domain.Models.MediaUser", b =>
                {
                    b.HasOne("UserService.Domain.Models.User", "User")
                        .WithMany("MediaUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserService.Domain.Models.User", b =>
                {
                    b.Navigation("AddedToFriends");

                    b.Navigation("BlockedByUsers");

                    b.Navigation("MediaUsers");

                    b.Navigation("MyBlackList");

                    b.Navigation("MyFriends");
                });
#pragma warning restore 612, 618
        }
    }
}
